### ISSUE TITLE
apply wrappy layout

### ISSUE THREAD

**Issue by AnhNDT** [prdlab/wrappy-android#1]
use "Design Proposal/Option 2"
- event "Wallet": show screen `Wrappy_mobile2-15.jpg`
- event "Wrappy": show screen tương tự ` .jpg`. Có link, click show http://www.zondir.top/wrappy/
(https://drive.google.com/drive/folders/0B6zJC3yHpwucX2NKeG5pLUpSQVU)

**Comment by nthtson** [comment]
Done

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#1
