### ISSUE TITLE
My page: showing Wrappy's user profile screen.

### ISSUE THREAD

**Issue by nthtson** [prdlab/wrappy-android#10]
Creating layouts: 
- Wrappy_mobile2-20.jpg
- Wrappy_mobile2-21.jpg
- Wrappy_mobile2-22.jpg
- Wrappy_mobile2-24.jpg (the first screen from left to right)

**Comment by nthtson** [comment]
Changing things :
- Change message from "Add Favourite successful" to "Added to Favourites successfully"
- If user's items are empty (None), please do not show them on sharing contact message.
- Should use plural labels: projects, favourites...
- Correct phone format.
- Show correct "Full name" and "Works" in view profile details.
- Sharing contact on list chat only displays "Wrappy" (single chat). It should be displayed as group chat. 
- Please remove " 's profile " after contact name, it's too long now. (my mistake)

**Comment by DuyKhanh88** [comment]
Done , please help me update and check this issue

**Comment by nthtson** [comment]
It's on #poc2 now. Thanks.

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#10
