### ISSUE TITLE
 My page: Updating Wrappy's user profile screens

### ISSUE THREAD

**Issue by nthtson** [prdlab/wrappy-android#11]
Making layouts for profile updating: full name, sex, birthday, language....

- Wrappy_mobile2-24.jpg (the second and third screens from left to right)
- Wrappy_mobile2-25.jpg
- Wrappy_mobile2-26.jpg

**Comment by nthtson** [comment]
Wrappy_mobile2-27.jpg

**Comment by nthtson** [comment]
Testing screens on POC2

**Comment by ben9505** [comment]
Done

**Comment by nthtson** [comment]
Is it possible to change the avatar of profile in "my page"? Please take a look on it. Thanks.

**Comment by nthtson** [comment]
Done.

Sharing profile, favorites are moved to #10

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#11
