### ISSUE TITLE
wallet function

### ISSUE THREAD

**Issue by AnhNDT** [prdlab/wrappy-android#2]
● cryptocurrency: ETH, PRO (Ethereum Token)
● wallet-functions: ref. to screen layout `Wrappy_mobile2-15.jpg` (https://drive.google.com/drive/folders/0B6zJC3yHpwucWDVDMHk4VnBVQVk)

**Comment by nthtson** [comment]
Done. Related to #9

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#2
