### ISSUE TITLE
update intro slides

### ISSUE THREAD

**Issue by AnhNDT** [prdlab/wrappy-android#6]
marketing team has edited intro message text such as below.
plz update slides.
```
1. Wrappy - Connect the world. This is the next-generation of SNS platform. 
2. Free - Wrappy is free forever: voice calls, video calls, TV conferences ...
3. Cloud - Wrappy allows you to access your messages from multiple devices.
4. Secure - Your messages are 100% encrypted and can be self-destructed.
5. Magic - You can easily send/ receive currencies to/ from friends.
6. Powerful – There’s no limit for your storage of media data and chat records.
7. Fast – You can send and receive messages instantly.
8. Privacy - You can delete your history at all time.
9. Ecology – A simple currency system.
10. Borderless – Currencies that can be used anywhere, from any country.
11. Revolution - A pioneer in an innovative & constantly evolving era.
```

1. Wrappy - Connect the world. This is **the next-generation of SNS** platform. 
2. Free - Wrappy is **free forever**: voice calls, video calls, TV conferences ...
3. Cloud - Wrappy allows you to access your messages **from multiple devices**.
4. Secure - Your messages are **100% encrypted** and can be self-destructed.
5. Magic - You can **easily send/ receive currencies** to/ from friends.
6. Powerful – There’s **no limit for your storage** of media data and chat records.
7. Fast – You can send and receive messages **instantly**.
8. Privacy - You can **delete your history at all time**.
9. Ecology – A simple **currency system**.
10. Borderless – Currencies that **can be used anywhere**, from any country.
11. Revolution - **A pioneer** in an innovative & constantly evolving era.

**Comment by DuyKhanh88** [comment]
Done, please update and help me review this issue
Thanks,

**Comment by nthtson** [comment]
@DuyKhanh88: Thanks. We're on it.

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#6
