### ISSUE TITLE
update menu items

### ISSUE THREAD

**Issue by AnhNDT** [prdlab/wrappy-android#8]
update menu items as below
[Settings ⇒ Wrappy Settings]: use `Settings` or `System Settings`  
[Settings ⇒ Proteusion Settings]: use `Wrappy Settings` and set new icon

**Comment by DuyKhanh88** [comment]
Done, Please help me review issue

**Comment by nthtson** [comment]
It's on poc1

**Comment by nthtson** [comment]
This issue was moved to prdlab/wrappy-android#8
